dist: xenial

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.6_Linux-64bit.deb
script:
  - hugo -v

deploy:
  local_dir: public
  repo: correl/correl.github.io
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: correl@gmail.com
  name: "Correl Roush"
  on:
    branch: ox-hugo
