language: go

go:
  - master # This uses automatically the latest version of go

install:
  - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: correl/correl.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: gh-pages # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: correl@gmail.com
  name: "Correl Roush"
  on:
    branch: master
