url: http://correl.phoenixinquis.net/
name: correl.phoenixinquis.net
description: projects and coding adventures

markdown: kramdown
exclude: ["*.org"]
gems: [jekyll-paginate]

paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
