url: http://correl.phoenixinquis.net/
name: correl.phoenixinquis.net
description: projects and coding adventures

markdown: redcarpet
exclude: ["*.org"]

paginate: 5

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
