baseURL = "http://example.org/"
languageCode = "en-us"
title = "Projects and Coding Adventures"
googleAnalytics = "UA-429788-2"
disqusShortname = "correl"
theme = "hugo-theme-m10c"
staticDir = ["static"]
pygmentsCodeFences = true
uglyUrls = true

[params]
  author = "Correl Roush"
  description = "Transgender ・ MtF ・ Genderfluid ・ She/Her"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/correlr"
  [[params.social]]
    name = "github"
    url = "https://github.com/correl"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/correlroush/"

[permalinks]
  blog = "/:year/:month/:day/:title"
