baseURL = "https://correl.phoenixinquis.net/"
languageCode = "en-us"
title = "Projects and Coding Adventures"
googleAnalytics = "UA-429788-2"
disqusShortname = "correl"
theme = "hugo-theme-m10c"
staticDir = ["static"]
pygmentsCodeFences = true
uglyUrls = true

[params]
  author = "Correl Roush"
  description = "Trans, tech-savvy, and a little silly. She/Her"
  [[params.social]]
    name = "github"
    url = "https://github.com/correl"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/correlroush/"

[permalinks]
  blog = "/:year/:month/:day/:slug"

[markup.goldmark.renderer]
unsafe = true
